resources:
- daemonset.yaml

patches:
- path: patch-selector.json
- path: patch-env.json

configMapGenerator:
- name: metrics-scripts
  files:
  - collect-metrics.sh
  - collect-cpu-metrics.sh
  - collect-container-metrics.sh
  - monitor.sh
  - entrypoint.sh

images:
- name: network-metrics
  newName: quay.io/akaris/must-gather-network-metrics:latest
